// Represents a user-defined goal with timeline, status, and point-tracking metadata.

using System.ComponentModel.DataAnnotations;
using GoalsTracker.Api.Models.Enums;

namespace GoalsTracker.Api.Models.Entities;

/// <summary>
/// A trackable objective set by a user, with a target date and point reward on completion.
/// </summary>
public class Goal
{
    /// <summary>Primary key.</summary>
    public int Id { get; set; }

    /// <summary>Foreign key to the owning user.</summary>
    public Guid UserId { get; set; }

    /// <summary>Short title describing the goal.</summary>
    [Required]
    [MaxLength(200)]
    public string Title { get; set; } = string.Empty;

    /// <summary>Optional longer description of the goal.</summary>
    [MaxLength(2000)]
    public string? Description { get; set; }

    /// <summary>The timeline category for this goal (weekly, monthly, or yearly).</summary>
    public TimelineType TimelineType { get; set; }

    /// <summary>Optional foreign key to a category.</summary>
    public int? CategoryId { get; set; }

    /// <summary>The date by which the goal should be completed.</summary>
    public DateOnly TargetDate { get; set; }

    /// <summary>Current status of the goal.</summary>
    public GoalStatus Status { get; set; } = GoalStatus.Active;

    /// <summary>UTC timestamp when the goal was marked as completed; null if not yet completed.</summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>Total points awarded for completing this goal (including bonuses).</summary>
    public int PointsAwarded { get; set; } = 0;

    /// <summary>Optional image URL or base64 data URL for the goal.</summary>
    [MaxLength(500)]
    public string? ImageUrl { get; set; }

    /// <summary>UTC timestamp when the goal was created.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>UTC timestamp when the goal was last updated.</summary>
    public DateTime UpdatedAt { get; set; }

    /// <summary>FK to the admin who assigned this goal; null if user-created.</summary>
    public Guid? AssignedByAdminId { get; set; }

    // Navigation properties

    /// <summary>The user who owns this goal.</summary>
    public User User { get; set; } = null!;

    /// <summary>The admin who assigned this goal, if applicable.</summary>
    public User? AssignedByAdmin { get; set; }

    /// <summary>Optional category assigned to this goal.</summary>
    public Category? Category { get; set; }

    /// <summary>Tags associated with this goal through the join entity.</summary>
    public ICollection<GoalTag> GoalTags { get; set; } = new List<GoalTag>();

    /// <summary>Point transactions generated by this goal.</summary>
    public ICollection<PointTransaction> PointTransactions { get; set; } = new List<PointTransaction>();
}
